# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  install-node:
    runs-on: ubuntu-latest
    env:
      USER_NAME   : ${{secrets.GIT_USERNAME}}
      USER_EMAIL  : ${{secrets.GIT_EMAIL}}}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn Install
        run: yarn

      - name: Next build
        run: yarn build

      - name: Next export
        run: yarn export
     
      - name: setting git email
        run: git config --global user.email $USER_EMAIL
      - name: setting git user name
        run: git config --global user.name $USER_NAME

      - name: deploy
        run: yarn deploy
