# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  install-node:
    env:
      MY_SECRET   : ${{ secrets.commit_secret }}
      USER_NAME   : tony14256
      USER_EMAIL  : tony14256@gmail.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn Install
        run: yarn

      - name: deploy
        run: |
          git init
          git config --local user.email $USER_NAME
          git config --local user.name $USER_EMAIL
          git status
          git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
          rm -rf node_modules/.cache
          yarn build
          yarn export
          touch out/.nojekyll
          git add out/ 
          git commit -m \"Deploy Next.js to gh-pages\" 
          git subtree push --prefix out origin gh-pages
          echo ðŸ¤˜ deploy gh-pages complete.
